# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MofilerAppObjC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MofilerAppObjC

if File.exist?("/Users/bryantafel/Documents/sdk-ios/Mofiler/Mofiler.h")
	pod 'Mofiler', :path => "/Users/bryantafel/Documents/sdk-ios/"
else
	pod 'Mofiler'
end

end
